[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30316
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = true

[rpc]
port = 8647
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x1dc850abbebd8a64ab2a4963211202db33ebba49"  
gas_floor_target = "40000000"
reseal_on_txs = "none" 
usd_per_tx = "0" 
force_sealing = true
refuse_service_transactions = false

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true

